{% set name = "sphinx_toml" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_toml-{{ version }}.tar.gz
  sha256: 40ad9f19ede9dbcff174f03292e8ea94a802e213a9bbb4295fcc63246fe3da91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.10
    - tomli
    - intersphinx-registry
    - pydantic

test:
  imports:
    - sphinx_toml
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Minimal package to load data from a sphinx.toml file next to a conf.py file.
  license: MIT
  license_file: LICENSE
  home: https://pypi.org/project/sphinx_toml

extra:
  recipe-maintainers:
    - Carreau
